name: Auto Build Flutter APK

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Ambil Kode (Checkout)
        uses: actions/checkout@v4

      - name: Siapkan Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Deteksi dan Set up Flutter & Dart SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # Gunakan 'any' jika pubspec.yaml tidak spesifik, atau sebutkan versi cadangan jika gagal dibaca
          flutter-version: 'any' 
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"

      - name: Jalankan Flutter Doctor
        run: flutter doctor -v

      - name: Ambil Dependensi (Pub Get)
        run: flutter pub get

      - name: Build Aplikasi (APK Release)
        run: flutter build apk --release

      - name: Simpan Hasil Build (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
